### ISSUE TITLE
Segment fault with Aquila::OouraFft::ifft()

### ISSUE THREAD

**Issue by sqbing** [zsiciarz/aquila#27]
I wrote a demo following examples/fft_filter.cpp.
Instead of using sine generator, i read a wav file as data source.
When size is big enough, say 44100, aquila cores with ifft().

Here is my gdb output:
(gdb) bt
#0  0x0000000100012e14 in cftmdl ()
#1  0x000000010000e950 in cftfsub ()
#2  0x000000010000e006 in cdft ()
#3  0x000000010000bc15 in Aquila::OouraFft::ifft ()
#4  0x0000000100001ce9 in main (argc=2, argv=0x7fff5fbffad0) at filter_wav.cpp:32

Code is here: https://gist.github.com/sqbing/8516543

Thank you.

**Comment by nginn** [comment]
Hi!
I've got the same error using code from example http://aquila-dsp.org/articles/updated-frequency-domain-filtering-example/ and my version of Aquila is 3.0.0.
So this error haven't been fixed before this release?
