### ISSUE TITLE
mfcc crashes

### ISSUE THREAD

**Issue by sqbing** [zsiciarz/aquila#44]
I'm trying to calculate mfcc for wav files as below, but crashes every time.
WaveFile->FramesCollection->Mfcc

Source code and lldb log have been uploaded to gist, https://gist.github.com/sqbing/13e7fba7342f96d54dfe

aquila version: dd83e58f231a369e7cc02074e6cba6999cb76b21
host: Mac OS X 10.10.2
compiler: clang-600.0.57

**Comment by zsiciarz** [comment]
Hi! I believe this is caused by having 1200 samples per frame - at the moment Aquila's fast FFT functions support only frame lengths that are powers of 2. Try changing to 1024 or 2048 samples per frame and see if it crashes.

**Comment by sqbing** [comment]
Solved, thank you for your help!
